(Dialog autobbox_quick_rename
    (Components
        (InputPanel NewNameInput)
        (PushButton RenameBtn)
        (PushButton CloneBtn)
        (PushButton CancelBtn)
    )
    (Resources
        (.Label "Quick Rename")
        (.TitleBar False)
        (.Resizeable False)
        (.DefaultButton "RenameBtn")
        (NewNameInput.Columns 24)
        (NewNameInput.MaxLen 31)
        (NewNameInput.TopOffset 6)
        (NewNameInput.BottomOffset 6)
        (NewNameInput.LeftOffset 6)
        (NewNameInput.RightOffset 6)
        (NewNameInput.AttachLeft True)
        (NewNameInput.AttachRight True)
        (RenameBtn.Label "Rename")
        (CloneBtn.Label "Clone")
        (CancelBtn.Label "Cancel")
        (RenameBtn.TopOffset 6)
        (RenameBtn.BottomOffset 6)
        (RenameBtn.RightOffset 2)
        (CloneBtn.TopOffset 6)
        (CloneBtn.BottomOffset 6)
        (CloneBtn.RightOffset 2)
        (CancelBtn.TopOffset 6)
        (CancelBtn.BottomOffset 6)
        (CancelBtn.RightOffset 6)
        (.Layout
            (Grid
                (Rows 0)
                (Cols 1 0 0 0)
                NewNameInput RenameBtn CloneBtn CancelBtn
            )
        )
    )
)
